#!/usr/bin/env python3
"""
Convert 001.wav .. 016.wav in a folder to a single wav_data.h for Arduino (PROGMEM).
Missing files get a short silence placeholder. Use for BabyBoomBox / RealBabyBoo sketches.

Usage:
  python tools/convert_all_wav_to_header.py [--folder PATH] [--output PATH] [--max-samples N]

  --folder   Directory containing 001.wav, 002.wav, ... 016.wav (default: babyboombox/RealBabyBoo)
  --output   Output header path (default: <folder>/wav_data.h)
  --max-samples  Max samples per file at 8 kHz (default: 1500 ~= 0.19 s; fits Uno flash)

Requirements: 8-bit or 16-bit WAV, any sample rate (resampled to 8 kHz), mono or stereo.
"""

import argparse
import struct
import wave
import os

TARGET_RATE = 8000
SILENCE_SAMPLES = 80  # placeholder length for missing files
# ~0.19 s at 8 kHz; 16 files fit in Uno flash (~24 KB)
DEFAULT_MAX_SAMPLES = 1500


def load_wav_to_8bit_mono(path, target_rate):
    with wave.open(path, "rb") as w:
        nch = w.getnchannels()
        sampwidth = w.getsampwidth()
        framerate = w.getframerate()
        nframes = w.getnframes()
        raw = w.readframes(nframes)

    if sampwidth == 1:
        samples = list(struct.unpack_from(f"{nframes * nch}B", raw))
    elif sampwidth == 2:
        fmt = f"<{nframes * nch}h"
        samples_int = struct.unpack_from(fmt, raw)
        samples = [max(0, min(255, (s >> 8) + 128)) for s in samples_int]
    else:
        raise ValueError("Unsupported sample width")

    if nch == 2:
        samples = [(samples[i] + samples[i + 1]) // 2 for i in range(0, len(samples), 2)]

    if framerate != target_rate:
        new_len = int(len(samples) * target_rate / framerate)
        resampled = []
        for i in range(new_len):
            idx = i * framerate / target_rate
            i0 = int(idx) % len(samples)
            i1 = (i0 + 1) % len(samples)
            frac = idx - int(idx)
            v = int(samples[i0] * (1 - frac) + samples[i1] * frac)
            resampled.append(max(0, min(255, v)))
        samples = resampled

    return samples


def write_header(out_path, arrays_and_lens, target_rate):
    with open(out_path, "w") as f:
        f.write("/* Generated by convert_all_wav_to_header.py - 8-bit mono, {} Hz */\n".format(target_rate))
        f.write("#ifndef WAV_DATA_H\n#define WAV_DATA_H\n\n")
        f.write("#include <avr/pgmspace.h>\n\n")

        for idx, (samples, length) in enumerate(arrays_and_lens):
            name = "wav_{:03d}".format(idx)
            f.write("const unsigned int {}_len = {};\n\n".format(name, length))
            f.write("const uint8_t {}[] PROGMEM = {{\n".format(name))
            for i in range(0, length, 16):
                chunk = samples[i : i + 16]
                line = ", ".join("0x{:02x}".format(b) for b in chunk)
                f.write("  {},\n".format(line))
            f.write("};\n\n")

        f.write("#endif /* WAV_DATA_H */\n")

    total = sum(l for _, l in arrays_and_lens)
    total_kb = total  # 1 byte per sample
    print("Wrote {}: 16 slots, {} total samples ({:.2f} s at {} Hz), ~{:.1f} KB in flash".format(
        out_path, total, total / target_rate, target_rate, total_kb / 1024.0))
    if total_kb > 28:
        print("  Note: Uno has ~32 KB flash total (code + data). Use --max-samples to shorten clips or use Mega2560.")


def main():
    parser = argparse.ArgumentParser(description="Convert 001.wav..016.wav to wav_data.h")
    parser.add_argument("--folder", default=None,
                        help="Folder containing 001.wav .. 016.wav (default: babyboombox/RealBabyBoo)")
    parser.add_argument("--output", default=None, help="Output .h path (default: <folder>/wav_data.h)")
    parser.add_argument("--max-samples", type=int, default=DEFAULT_MAX_SAMPLES,
                        help="Max samples per file at 8 kHz (default %d ~= 0.19 s)" % DEFAULT_MAX_SAMPLES)
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    rel_folder = args.folder or os.path.join("babyboombox", "RealBabyBoo")
    folder = os.path.join(repo_root, rel_folder) if not os.path.isabs(rel_folder) else rel_folder
    folder = os.path.normpath(folder)
    if not os.path.isdir(folder):
        os.makedirs(folder, exist_ok=True)
        print("Created folder:", folder)

    out_path = args.output or os.path.join(folder, "wav_data.h")
    max_samples = args.max_samples
    silence = [0x80] * SILENCE_SAMPLES

    arrays_and_lens = []
    for i in range(16):
        fname = "{:03d}.wav".format(i + 1)
        path = os.path.join(folder, fname)
        if os.path.isfile(path):
            try:
                samples = load_wav_to_8bit_mono(path, TARGET_RATE)
                samples = samples[:max_samples]
                arrays_and_lens.append((samples, len(samples)))
                print("  {} -> {} samples".format(fname, len(samples)))
            except Exception as e:
                print("  {} skip: {}".format(fname, e))
                arrays_and_lens.append((silence, SILENCE_SAMPLES))
        else:
            arrays_and_lens.append((silence, SILENCE_SAMPLES))

    write_header(out_path, arrays_and_lens, TARGET_RATE)


if __name__ == "__main__":
    main()
